server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: microservicio-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: experiencia
            uri: http://localhost:8093
            predicates:
              - Path=/api/experiencia/**
          - id: personal
            uri: http://localhost:8090
            predicates:
              - Path=/api/personal/**
          - id: proyecto
            uri: http://localhost:8091
            predicates:
              - Path=/api/proyecto/**
          - id: idioma
            uri: http://localhost:8090
            predicates:
              - Path=/api/idioma/**
          - id: habilidades
            uri: http://localhost:8092
            predicates:
              - Path=/api/habilidades/**
          