server:
  port: 8093

spring:
  application:
    name: microservicio-experiencia
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/experienciadb
    username: root
    password:
  jpa:
    hibernate:
      dll-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect



eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

